# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

parameters:

services:
  app.util.api_wrapper:
    class: AppBundle\Util\ApiWrapper
    arguments: ['%app.api_token%']

  app.util.goal_collection_builder:
    class: AppBundle\Util\GoalCollectionBuilder
    arguments: ['%app.defaultBuilderOptions%']

  app.util.simple_event_builder:
    class: AppBundle\Util\SimpleEventBuilder
    tags:
      - {name: app.goal_builder, alias: simpleEvent}

  app.util.multiple_event_goal_builder:
    class: AppBundle\Util\MultipleEventGoalBuilder
    tags:
      - {name: app.goal_builder, alias: multipleEvents}
